const FLAGS: Record<string, string> = {
  argentina: '🇦🇷',
  australia: '🇦🇺',
  austria: '🇦🇹',
  albania: '🇦🇱',
  algeria: '🇩🇿',
  belgium: '🇧🇪',
  bolivia: '🇧🇴',
  'bosnia-herzegovina': '🇧🇦',
  brazil: '🇧🇷',
  cameroon: '🇨🇲',
  canada: '🇨🇦',
  chile: '🇨🇱',
  colombia: '🇨🇴',
  'costa rica': '🇨🇷',
  croatia: '🇭🇷',
  czechia: '🇨🇿',
  'czech republic': '🇨🇿',
  denmark: '🇩🇰',
  ecuador: '🇪🇨',
  egypt: '🇪🇬',
  england: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  finland: '🇫🇮',
  france: '🇫🇷',
  georgia: '🇬🇪',
  germany: '🇩🇪',
  ghana: '🇬🇭',
  greece: '🇬🇷',
  honduras: '🇭🇳',
  hungary: '🇭🇺',
  iran: '🇮🇷',
  iraq: '🇮🇶',
  ireland: '🇮🇪',
  israel: '🇮🇱',
  italy: '🇮🇹',
  'ivory coast': '🇨🇮',
  "côte d'ivoire": '🇨🇮',
  japan: '🇯🇵',
  'korea republic': '🇰🇷',
  'south korea': '🇰🇷',
  mali: '🇲🇱',
  mexico: '🇲🇽',
  morocco: '🇲🇦',
  netherlands: '🇳🇱',
  'new zealand': '🇳🇿',
  nigeria: '🇳🇬',
  'north macedonia': '🇲🇰',
  norway: '🇳🇴',
  panama: '🇵🇦',
  paraguay: '🇵🇾',
  peru: '🇵🇪',
  poland: '🇵🇱',
  portugal: '🇵🇹',
  qatar: '🇶🇦',
  romania: '🇷🇴',
  'saudi arabia': '🇸🇦',
  scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  senegal: '🇸🇳',
  serbia: '🇷🇸',
  slovakia: '🇸🇰',
  slovenia: '🇸🇮',
  'south africa': '🇿🇦',
  spain: '🇪🇸',
  sweden: '🇸🇪',
  switzerland: '🇨🇭',
  tunisia: '🇹🇳',
  turkey: '🇹🇷',
  ukraine: '🇺🇦',
  'united states': '🇺🇸',
  usa: '🇺🇸',
  uruguay: '🇺🇾',
  uzbekistan: '🇺🇿',
  venezuela: '🇻🇪',
  wales: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
}

export function getFlag(team: string): string {
  return FLAGS[team.toLowerCase()] ?? '🏳️'
}
